name: Create Plugin Release

on:
  push:
    tags:
      - 'v*'  # Trigger when new tags starting with 'v' are pushed

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '24'
        cache: 'npm'

    - name: Install npm dependencies
      run: npm ci

    - name: Build React assets
      run: npm run build

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: composer

    - name: Install Composer dependencies (production only)
      run: composer install --no-dev --optimize-autoloader

    - name: Create plugin ZIP file
      run: |
        # Create temporary directory for build
        mkdir contact-form-app-build
        
        # Copy main plugin files
        cp contact-form-app.php composer.json index.php LICENSE.txt uninstall.php contact-form-app-build/
        
        # Copy directories while preserving structure
        cp -r functions internals ajax engine frontend backend cli integrations languages rest templates contact-form-app-build/
        
        # Copy assets directory and its contents
        mkdir -p contact-form-app-build/assets
        cp -r assets/* contact-form-app-build/assets/
        
        # Copy vendor directory and its contents
        mkdir -p contact-form-app-build/vendor
        cp -r vendor/* contact-form-app-build/vendor/
        
        # Remove unwanted files from vendor directory
        find contact-form-app-build/vendor -name "*.sh" -delete
        find contact-form-app-build/vendor -name ".git*" -exec rm -rf {} +
        find contact-form-app-build/vendor -name ".*" -not -path "." -delete
        
        # Copy README if exists
        [ -f README.txt ] && cp README.txt contact-form-app-build/
        
        # Create the final ZIP file
        cd contact-form-app-build && zip -r ../contact-form-app.zip . -x ".*"

    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: contact-form-app.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    